---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: linkding-
resources:
- ../../../../base
patches:
  - path: patch.yaml
    target:
      kind: CronJob
      name: torus-backup
