auth:
  secret-key: ${GLANCE_TOKEN} 
  users:
    tstarr:
      password: ${GLANCE_PASSWORD}

custom-widgets:
  - $include: linkding.yml

pages:
  - $include: home.yml
  - $include: lab.yml
  - $include: work.yml
