- name: Home 
  width: default 
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: Asia/Shanghai
              label: Beijing
            - timezone: Europe/Moscow
              label: Moscow
            - timezone: Asia/Tehran
              label: Tehran
        - type: calendar
          first-day-of-week: monday
        - type: weather
          units: imperial 
          hour-format: 24h
          location: Tehachapi, United States
        
    - size: full
      widgets:
        - type: search
          search-engine: google
          new-tab: true
        - type: split-column
          max-columns: 2 
          widgets: 
            - <<: *linkding
              title: Daily
              url: https://link.tstarr.us/api/bookmarks?bundle=3&sort=title_asc
            - <<: *linkding
              title: Media 
              url: https://link.tstarr.us/api/bookmarks?bundle=6&sort=title_asc
            - <<: *linkding
              title: Social 
              url: https://link.tstarr.us/api/bookmarks?bundle=8&sort=title_asc
            - <<: *linkding
              title: Shop 
              url: https://link.tstarr.us/api/bookmarks?bundle=9&sort=title_asc

    - size: small
      widgets:
        - $include: sports.yml
