---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remmina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remmina
  template:
    metadata:
      labels:
        app: remmina
    spec:
      securityContext:
        fsGroup: 104
      containers:
        - image: lscr.io/linuxserver/remmina:latest
          name: remmina
          ports:
            - containerPort: 3000 
              protocol: TCP
          volumeMounts:
            - name: remmina-volume
              mountPath: /config
            - name: remmina-gpu-volume
              mountPath: /dev/dri
          env:
            - name: PUID 
              value: "1000"
            - name: PGID 
              value: "1000"
            - name: TZ 
              value: "America/Los_Angeles"
            - name: DRINODE
              value: "/dev/dri/renderD128"
          securityContext:
            privileged: true
      volumes:
        - name: remmina-volume
          persistentVolumeClaim:
            claimName: remmina-pvc
        - name: remmina-gpu-volume
          hostPath:
            path: /dev/dri
      restartPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
