---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: linkding-
resources:
- ../../../../base/backups
patches:
  - path: rsync-patch.yaml
    target:
      kind: CronJob
      name: rsync-backup
  - path: torus-patch.yaml
    target:
      kind: CronJob
      name: torus-backup
