---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db-service
spec:
  selector:
    app: nextcloud-db
  ports:
    - name: nextcloud-db
      port: 3306 
      targetPort: 3306
      nodePort: 30306
  type: NodePort 
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
