---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: glance.v1.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance-service
                port:
                  number: 80
