apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: glance-config 
  files:
    - config/glance.yml
    - config/home.yml
    - config/lab.yml
    - config/linkding.yml
    - config/sports.yml
    - config/work.yml
