---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux-db
  template:
    metadata:
      labels:
        app: miniflux-db
    spec:
      containers:
        - image: postgres:18
          name: miniflux-db
          ports:
            - containerPort: 5432 
              protocol: TCP
          volumeMounts:
            - name: miniflux-db-volume
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_USER
              value: "miniflux"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: MF_POSTGRES_PASSWORD 
            - name: POSTGRES_DB
              value: "miniflux"
      volumes:
        - name: miniflux-db-volume
          persistentVolumeClaim:
            claimName: miniflux-db-pvc
      restartPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - image: miniflux/miniflux:latest
          name: miniflux
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: LOG_LEVEL 
              value: "debug" 
            - name: POLLING_FREQUENCY 
              value: "5" 
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
            - name: ADMIN_USERNAME
              value: admin
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: MF_ADMIN_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: MF_POSTGRES_PASSWORD
            - name: DATABASE_URL 
              value: postgres://miniflux:$(POSTGRES_PASSWORD)@miniflux-db-service:5432/miniflux?sslmode=disable
      restartPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
