---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux-db
  template:
    metadata:
      labels:
        app: miniflux-db
    spec:
      containers:
        - image: postgres:18
          name: miniflux-db
          ports:
            - containerPort: 5432 
              protocol: TCP
          volumeMounts:
            - name: miniflux-db-volume
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_USER
              value: "miniflux"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: MF_POSTGRES_PASSWORD 
            - name: POSTGRES_DB
              value: "miniflux"
      volumes:
        - name: miniflux-db-volume
          persistentVolumeClaim:
            claimName: miniflux-db-pvc
      restartPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mattermost
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: mattermost
#  template:
#    metadata:
#      labels:
#        app: mattermost
#    spec:
#      containers:
#        - image: mattermost/mattermost-team-edition:10.4.2
#          name: mattermost
#          ports:
#            - containerPort: 8065
#              protocol: TCP
#          volumeMounts:
#            - name: mattermost-config-volume
#              mountPath: /mattermost/config
#            - name: mattermost-data-volume
#              mountPath: /mattermost/data
#            - name: mattermost-logs-volume
#              mountPath: /mattermost/logs
#          env:
#            - name: TZ 
#              value: "America/Los_Angeles"
#            - name: MM_SQLSETTINGS_DRIVERNAME
#              value: "postgres"
#            - name: MM_SQLSETTINGS_DATASOURCE
#              valueFrom:
#                secretKeyRef:
#                  name: sops-apps-dev
#                  key: MM_SQLSETTINGS_DATASOURCE
#            - name: MM_BLEVESETTINGS_INDEXDIR
#              value: "/mattermost/bleve-indexes"
#            - name: MM_SERVICESETTINGS_SITEURL
#              value: "https://lc.tstarr.us"
#      volumes:
#        - name: mattermost-config-volume
#          persistentVolumeClaim:
#            claimName: mattermost-config-pvc
#        - name: mattermost-data-volume
#          persistentVolumeClaim:
#            claimName: mattermost-data-pvc
#        - name: mattermost-logs-volume
#          persistentVolumeClaim:
#            claimName: mattermost-logs-pvc
#      restartPolicy: Always
#    strategy:
#      type: RollingUpdate
#      rollingUpdate:
#        maxUnavailable: 25%
#        maxSurge: 25%
