---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-db-service
spec:
  selector:
    app: miniflux-db
  ports:
    - name: miniflux-db
      port: 5432 
      targetPort: 5432
      nodePort: 30434
  type: NodePort 
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-service
spec:
  selector:
    app: miniflux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
