---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twof-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twof-auth
  template:
    metadata:
      labels:
        app: twof-auth
    spec:
      containers:
        - image: 2fauth/2fauth:latest
          name: twof-auth
          ports:
            - containerPort: 8000 
              protocol: TCP
          volumeMounts:
            - name: twof-auth-volume
              mountPath: /2fauth
          env:
            - name: APP_TIMEZONE 
              value: "America/Los_Angeles"
            - name: SITE_OWNER 
              value: "starrtyler88@gmail.com"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: TWOF_AUTH_APP_KEY 
            - name: APP_URL 
              value: "http://2fa.tstarr.us"
            - name: MAIL_MAILER
              value: "smtp"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: TWOF_AUTH_MAIL_ADDRESS 
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: TWOF_AUTH_MAIL_PASSWORD 
            - name: MAIL_ENCRYPTION
              value: "tls"
            - name: MAIL_FROM_NAME
              value: "2fauth"
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: sops-apps-dev
                  key: TWOF_AUTH_MAIL_ADDRESS 
      volumes:
        - name: twof-auth-volume
          persistentVolumeClaim:
            claimName: twof-auth-pvc
      restartPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
