---
apiVersion: v1
kind: Service
metadata:
  name: homedb-service
spec:
  selector:
    app: homedb
  ports:
    - name: postgres 
      port: 5432
      targetPort: 5432 
      nodePort: 30432
  type: NodePort 
