---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkding-ingress
  namespace: linkding
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`vortex-1`)
      services:
        - kind: Service
          name: linkding
          port: 9090
