apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: vortex-1
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linkding-service
                port:
                  number: 80
