apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`glance.vortex-1.lan`) || Host(`glance.tstarr.us`)
      kind: Rule
      services:
        - name: glance-service
          port: 80

    - match: Host(`link.vortex-1.lan`) || Host(`link.tstarr.us`)
      kind: Rule
      services:
        - name: linkding-service
          port: 80

    - match: Host(`rdp.vortex-1.lan`) || Host(`rdp.tstarr.us`)
      kind: Rule
      services:
        - name: remmina-service
          port: 80

    - match: Host(`code.vortex-1.lan`) || Host(`code.tstarr.us`)
      kind: Rule
      services:
        - name: code-server-service
          port: 80

    - match: Host(`media.vortex-1.lan`) || Host(`media.tstarr.us`)
      kind: Rule
      services:
        - name: jellyfin-service
          port: 80

    - match: Host(`2fa.vortex-1.lan`) || Host(`2fa.tstarr.us`)
      kind: Rule
      services:
        - name: twof-auth-service
          port: 80
