apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`glance.v1.lan`) || Host(`glance.tstarr.us`)
      kind: Rule
      services:
        - name: glance-service
          port: 80

    - match: Host(`link.v1.lan`) || Host(`link.tstarr.us`)
      kind: Rule
      services:
        - name: linkding-service
          port: 80
