apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflare-ddns
  - ./code-server
  - ./jellyfin
  - ./gitea
  - ./glance
  - ./linkding
  - ./nextcloud
  - ./remmina
  - ./twof-auth
  - ingress.yaml
  - secrets.yaml
