---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-db-service
spec:
  selector:
    app: mattermost-db
  ports:
    - name: mattermost-db
      port: 5432 
      targetPort: 5432
      nodePort: 30433
  type: NodePort 
---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-service
spec:
  selector:
    app: mattermost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8065
  type: ClusterIP
